// AUTO-GENERATED FILE. DO NOT MODIFY DIRECTLY.

export const Errors = {
  ErrorSavingDatabase: "errors:ErrorSavingDatabase",
  IncorrectUsernamePassword: "errors:IncorrectUsernamePassword",
  InvalidRefreshToken: "errors:InvalidRefreshToken",
  NameFieldRequired: "errors:NameFieldRequired",
  NotFound: "errors:NotFound",
  PasswordCannotBeServed: "errors:PasswordCannotBeServed",
  PasswordCannotBeTransfered: "errors:PasswordCannotBeTransfered",
  PasswordNotFound: "errors:PasswordNotFound",
  PasswordRequestNull: "errors:PasswordRequestNull",
  RefreshTokenNotFound: "errors:RefreshTokenNotFound",
  RegisterAlreadyExists: "errors:RegisterAlreadyExists",
  ServiceTypeNotFound: "errors:ServiceTypeNotFound",
  UserAlreadyHasRole: "errors:UserAlreadyHasRole",
  UserNotFound: "errors:UserNotFound",
  UserTemporarilyBlocked: "errors:UserTemporarilyBlocked",
  ErrorLoadingAvailableQueues: "errors:ErrorLoadingAvailableQueues",
  UnexpectedErrorGeneratingPassword: "errors:UnexpectedErrorGeneratingPassword",
  FillAllFields: "errors:FillAllFields",
  UnexpectedError: "errors:UnexpectedError",
} as const;

export const Labels = {
  NoServiceLocation: "labels:NoServiceLocation",
  ServiceLocator: "labels:ServiceLocator",
  SystemAccess: "labels:SystemAccess",
  EnterCredentials: "labels:EnterCredentials",
  Email: "labels:Email",
  Password: "labels:Password",
  EnterButton: "labels:EnterButton",
  GoBackButton: "labels:GoBackButton",
  NavigationHome: "labels:NavigationHome",
  NavigationService: "labels:NavigationService",
  NavigationLogin: "labels:NavigationLogin",
  NavigationPreferential: "labels:NavigationPreferential",
  NavigationExamRetrieval: "labels:NavigationExamRetrieval",
  NavigationSettings: "labels:NavigationSettings",
  ThemeSelectionTitle: "labels:ThemeSelectionTitle",
  ThemeSelectionSubtitle: "labels:ThemeSelectionSubtitle",
  ThemeLight: "labels:ThemeLight",
  ThemeDark: "labels:ThemeDark",
  ThemeSystem: "labels:ThemeSystem",
  SettingsGeneral: "labels:SettingsGeneral",
  SettingsThemes: "labels:SettingsThemes",
  SettingsLanguages: "labels:SettingsLanguages",
  SettingsInformation: "labels:SettingsInformation",
  SettingsAboutApp: "labels:SettingsAboutApp",
  SettingsTerms: "labels:SettingsTerms",
  SettingsPrivacy: "labels:SettingsPrivacy",
} as const;

export const Messages = {
  ActiveUser: "messages:ActiveUser",
  AwaitingNextPassword: "messages:AwaitingNextPassword",
  CallingNextPassword: "messages:CallingNextPassword",
  HistoryQueueChanged: "messages:HistoryQueueChanged",
  HistoryServed: "messages:HistoryServed",
  HistoryTransferred: "messages:HistoryTransferred",
  InactivatedUser: "messages:InactivatedUser",
  NoPasswordsInQueue: "messages:NoPasswordsInQueue",
  UnableCreateServiceLocation: "messages:UnableCreateServiceLocation",
  LoadingSystem: "messages:LoadingSystem",
  Welcome: "messages:Welcome",
  Logout: "messages:Logout",
  LoggedOutSuccess: "messages:LoggedOutSuccess",
  PasswordGeneratedFor: "messages:PasswordGeneratedFor",
  TypeOfService: "messages:TypeOfService",
  ChooseServiceType: "messages:ChooseServiceType",
  Common: "messages:Common",
  Preferential: "messages:Preferential",
  WelcomeBack: "messages:WelcomeBack",
} as const;

