//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Totem.Common.Localization.Resources {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Errors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Errors() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Totem.Common.Localization.Resources.Errors", typeof(Errors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a CORS: &apos;AllowedOrigins&apos; não está configurado no appsettings.json..
        /// </summary>
        public static string CorsAllowedOriginsNotConfigured {
            get {
                return ResourceManager.GetString("CorsAllowedOriginsNotConfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O e-mail de confirmação não confere com o novo e-mail..
        /// </summary>
        public static string EmailConfirmationMismatch {
            get {
                return ResourceManager.GetString("EmailConfirmationMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Erro ao carregar filas disponíveis.
        /// </summary>
        public static string ErrorLoadingAvailableQueues {
            get {
                return ResourceManager.GetString("ErrorLoadingAvailableQueues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Erro ao Salvar no Banco de dados. .
        /// </summary>
        public static string ErrorSavingDatabase {
            get {
                return ResourceManager.GetString("ErrorSavingDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Por favor, preencha todos os campos..
        /// </summary>
        public static string FillAllFields {
            get {
                return ResourceManager.GetString("FillAllFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O {0} deve ter entre {2} e {1} caracteres..
        /// </summary>
        public static string GenericFieldMustBeRange {
            get {
                return ResourceManager.GetString("GenericFieldMustBeRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O valor de &apos;{0}&apos; não pode ser igual ao de &apos;{1}&apos;..
        /// </summary>
        public static string GenericValueCannotBeEqual {
            get {
                return ResourceManager.GetString("GenericValueCannotBeEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Usuário ou senha incorretos..
        /// </summary>
        public static string IncorrectUsernamePassword {
            get {
                return ResourceManager.GetString("IncorrectUsernamePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O {0} está em um formato inválido..
        /// </summary>
        public static string InvalidFormat {
            get {
                return ResourceManager.GetString("InvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não foi possível atualizar sua permissão..
        /// </summary>
        public static string InvalidRefreshToken {
            get {
                return ResourceManager.GetString("InvalidRefreshToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O Campo Nome deve ter entre {2} e {1} caracteres..
        /// </summary>
        public static string NameFieldLengthRange {
            get {
                return ResourceManager.GetString("NameFieldLengthRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O campo Nome é obrigatório.
        /// </summary>
        public static string NameFieldRequired {
            get {
                return ResourceManager.GetString("NameFieldRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O Nome deve ter entre {2} e {1} caracteres..
        /// </summary>
        public static string NameLengthRange {
            get {
                return ResourceManager.GetString("NameLengthRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Registro não encontrado..
        /// </summary>
        public static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A nova senha não pode ser igual à senha anterior..
        /// </summary>
        public static string PasswordCannotBeEqual {
            get {
                return ResourceManager.GetString("PasswordCannotBeEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Uma senha sem local de atendimento, não pode ser atendida..
        /// </summary>
        public static string PasswordCannotBeServed {
            get {
                return ResourceManager.GetString("PasswordCannotBeServed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Uma senha atendida não pode ser transferida..
        /// </summary>
        public static string PasswordCannotBeTransfered {
            get {
                return ResourceManager.GetString("PasswordCannotBeTransfered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A nova senha e a confirmação não conferem..
        /// </summary>
        public static string PasswordConfirmationMismatch {
            get {
                return ResourceManager.GetString("PasswordConfirmationMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A senha deve ter entre {2} e {1} caracteres..
        /// </summary>
        public static string PasswordLengthRange {
            get {
                return ResourceManager.GetString("PasswordLengthRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Senha não encontrada..
        /// </summary>
        public static string PasswordNotFound {
            get {
                return ResourceManager.GetString("PasswordNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O campo senha não pode ser nulo.
        /// </summary>
        public static string PasswordRequestNull {
            get {
                return ResourceManager.GetString("PasswordRequestNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a As senhas não conferem..
        /// </summary>
        public static string PasswordsMismatch {
            get {
                return ResourceManager.GetString("PasswordsMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A lista de permissões não pode estar vazia..
        /// </summary>
        public static string PermissionListCannotBeEmpty {
            get {
                return ResourceManager.GetString("PermissionListCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Propriedade &apos;{0}&apos; não encontrada..
        /// </summary>
        public static string PropertyNotFound {
            get {
                return ResourceManager.GetString("PropertyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Sessão expirada. Faça login novamente..
        /// </summary>
        public static string RefreshTokenExpired {
            get {
                return ResourceManager.GetString("RefreshTokenExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Token de atualização não encontrado..
        /// </summary>
        public static string RefreshTokenNotFound {
            get {
                return ResourceManager.GetString("RefreshTokenNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Registro  já existe..
        /// </summary>
        public static string RegisterAlreadyExists {
            get {
                return ResourceManager.GetString("RegisterAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Tipo de serviço não encontrado..
        /// </summary>
        public static string ServiceTypeNotFound {
            get {
                return ResourceManager.GetString("ServiceTypeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ocorreu um erro inesperado. Tente novamente..
        /// </summary>
        public static string UnexpectedError {
            get {
                return ResourceManager.GetString("UnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Erro inesperado ao gerar senha.
        /// </summary>
        public static string UnexpectedErrorGeneratingPassword {
            get {
                return ResourceManager.GetString("UnexpectedErrorGeneratingPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Usuário já possui esta função..
        /// </summary>
        public static string UserAlreadyHasRole {
            get {
                return ResourceManager.GetString("UserAlreadyHasRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Usuário Inativo..
        /// </summary>
        public static string UserInactive {
            get {
                return ResourceManager.GetString("UserInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Usuario não encontrado.
        /// </summary>
        public static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Usuário temporariamente bloqueado por tentativas inválidas..
        /// </summary>
        public static string UserTemporarilyBlocked {
            get {
                return ResourceManager.GetString("UserTemporarilyBlocked", resourceCulture);
            }
        }
    }
}
