//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Totem.Common.Localization.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Errors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Errors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Totem.Common.Localization.Resources.Errors", typeof(Errors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao carregar filas disponíveis.
        /// </summary>
        public static string ErrorLoadingAvailableQueues {
            get {
                return ResourceManager.GetString("ErrorLoadingAvailableQueues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao Salvar no Banco de dados. .
        /// </summary>
        public static string ErrorSavingDatabase {
            get {
                return ResourceManager.GetString("ErrorSavingDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, preencha todos os campos..
        /// </summary>
        public static string FillAllFields {
            get {
                return ResourceManager.GetString("FillAllFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O valor de &apos;{0}&apos; não pode ser igual ao de &apos;{1}&apos;..
        /// </summary>
        public static string GenericValueCannotBeEqual {
            get {
                return ResourceManager.GetString("GenericValueCannotBeEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário ou senha incorretos..
        /// </summary>
        public static string IncorrectUsernamePassword {
            get {
                return ResourceManager.GetString("IncorrectUsernamePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possível atualizar sua permissão..
        /// </summary>
        public static string InvalidRefreshToken {
            get {
                return ResourceManager.GetString("InvalidRefreshToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo Nome é obrigatório.
        /// </summary>
        public static string NameFieldRequired {
            get {
                return ResourceManager.GetString("NameFieldRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro não encontrado..
        /// </summary>
        public static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A nova senha não pode ser igual à senha anterior..
        /// </summary>
        public static string PasswordCannotBeEqual {
            get {
                return ResourceManager.GetString("PasswordCannotBeEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uma senha sem local de atendimento, não pode ser atendida..
        /// </summary>
        public static string PasswordCannotBeServed {
            get {
                return ResourceManager.GetString("PasswordCannotBeServed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uma senha atendida não pode ser transferida..
        /// </summary>
        public static string PasswordCannotBeTransfered {
            get {
                return ResourceManager.GetString("PasswordCannotBeTransfered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senha não encontrada..
        /// </summary>
        public static string PasswordNotFound {
            get {
                return ResourceManager.GetString("PasswordNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo senha não pode ser nulo.
        /// </summary>
        public static string PasswordRequestNull {
            get {
                return ResourceManager.GetString("PasswordRequestNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Propriedade &apos;{0}&apos; não encontrada..
        /// </summary>
        public static string PropertyNotFound {
            get {
                return ResourceManager.GetString("PropertyNotFound", resourceCulture);
            }
        }
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A lista de permissões não pode estar vazia..
        /// </summary>
        public static string PermissionListCannotBeEmpty
        {
            get
            {
                return ResourceManager.GetString("PermissionListCannotBeEmpty", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Sessão expirada. Faça login novamente..
        /// </summary>
        public static string RefreshTokenExpired {
            get {
                return ResourceManager.GetString("RefreshTokenExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token de atualização não encontrado..
        /// </summary>
        public static string RefreshTokenNotFound {
            get {
                return ResourceManager.GetString("RefreshTokenNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro  já existe..
        /// </summary>
        public static string RegisterAlreadyExists {
            get {
                return ResourceManager.GetString("RegisterAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de serviço não encontrado..
        /// </summary>
        public static string ServiceTypeNotFound {
            get {
                return ResourceManager.GetString("ServiceTypeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu um erro inesperado. Tente novamente..
        /// </summary>
        public static string UnexpectedError {
            get {
                return ResourceManager.GetString("UnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro inesperado ao gerar senha.
        /// </summary>
        public static string UnexpectedErrorGeneratingPassword {
            get {
                return ResourceManager.GetString("UnexpectedErrorGeneratingPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário já possui esta função..
        /// </summary>
        public static string UserAlreadyHasRole {
            get {
                return ResourceManager.GetString("UserAlreadyHasRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario não encontrado.
        /// </summary>
        public static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Usuário Inativo..
        /// </summary>
        public static string UserInactive
        {
            get
            {
                return ResourceManager.GetString("UserInactive", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to Usuário temporariamente bloqueado por tentativas inválidas..
        /// </summary>
        public static string UserTemporarilyBlocked {
            get {
                return ResourceManager.GetString("UserTemporarilyBlocked", resourceCulture);
            }
        }
    }
}
