//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Totem.Common.Localization.Resources {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Totem.Common.Localization.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Usuário ativo..
        /// </summary>
        public static string ActiveUser {
            get {
                return ResourceManager.GetString("ActiveUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Aguardando próxima senha da fila..
        ///   Looks up a localized string similar to Chamando próxima senha da fila..
        /// </summary>
        public static string CallingNextPassword {
            get {
                return ResourceManager.GetString("CallingNextPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senha {0} transferida da fila “{1}” para “{2}”.
        /// </summary>
        public static string HistoryQueueChanged {
            get {
                return ResourceManager.GetString("HistoryQueueChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senha {0} marcada como atendida.
        /// </summary>
        public static string HistoryServed {
            get {
                return ResourceManager.GetString("HistoryServed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senha {0} transferida de “{1}” para “{2}”.
        /// </summary>
        public static string HistoryTransferred {
            get {
                return ResourceManager.GetString("HistoryTransferred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Usuario inativado..
        /// </summary>
        public static string InactivatedUser {
            get {
                return ResourceManager.GetString("InactivatedUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Usuario inativado..
        /// </summary>
        public static string InactivatedUser {
            get {
                return ResourceManager.GetString("InactivatedUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não há senhas na fila. Aguarde..
        /// </summary>
        public static string NoPasswordsInQueue {
            get {
                return ResourceManager.GetString("NoPasswordsInQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não foi possível criar o Local de Atendimento.
        /// </summary>
        public static string UnableCreateServiceLocation {
            get {
                return ResourceManager.GetString("UnableCreateServiceLocation", resourceCulture);
            }
        }
    }
}
