//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Totem.Common.Localization.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Totem.Common.Localization.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário ativo..
        /// </summary>
        public static string ActiveUser {
            get {
                return ResourceManager.GetString("ActiveUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aguardando próxima senha da fila..
        /// </summary>
        public static string AwaitingNextPassword {
            get {
                return ResourceManager.GetString("AwaitingNextPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chamando próxima senha da fila..
        /// </summary>
        public static string CallingNextPassword {
            get {
                return ResourceManager.GetString("CallingNextPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escolha o tipo de atendimento desejado:.
        /// </summary>
        public static string ChooseServiceType {
            get {
                return ResourceManager.GetString("ChooseServiceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comum.
        /// </summary>
        public static string Common {
            get {
                return ResourceManager.GetString("Common", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senha {0} transferida da fila “{1}” para “{2}”.
        /// </summary>
        public static string HistoryQueueChanged {
            get {
                return ResourceManager.GetString("HistoryQueueChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senha {0} marcada como atendida.
        /// </summary>
        public static string HistoryServed {
            get {
                return ResourceManager.GetString("HistoryServed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senha {0} transferida de “{1}” para “{2}”.
        /// </summary>
        public static string HistoryTransferred {
            get {
                return ResourceManager.GetString("HistoryTransferred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario inativado..
        /// </summary>
        public static string InactivatedUser {
            get {
                return ResourceManager.GetString("InactivatedUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carregando sistema....
        /// </summary>
        public static string LoadingSystem {
            get {
                return ResourceManager.GetString("LoadingSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Você saiu com sucesso!.
        /// </summary>
        public static string LoggedOutSuccess {
            get {
                return ResourceManager.GetString("LoggedOutSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sair da Conta.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não há senhas na fila. Aguarde..
        /// </summary>
        public static string NoPasswordsInQueue {
            get {
                return ResourceManager.GetString("NoPasswordsInQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senha gerada para:.
        /// </summary>
        public static string PasswordGeneratedFor {
            get {
                return ResourceManager.GetString("PasswordGeneratedFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferencial.
        /// </summary>
        public static string Preferential {
            get {
                return ResourceManager.GetString("Preferential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de Atendimento.
        /// </summary>
        public static string TypeOfService {
            get {
                return ResourceManager.GetString("TypeOfService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possível criar o Local de Atendimento.
        /// </summary>
        public static string UnableCreateServiceLocation {
            get {
                return ResourceManager.GetString("UnableCreateServiceLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bem-vindo,.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bem-vindo de volta!.
        /// </summary>
        public static string WelcomeBack {
            get {
                return ResourceManager.GetString("WelcomeBack", resourceCulture);
            }
        }
    }
}
