//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Totem.Common.Localization.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Totem.Common.Localization.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chamando próxima senha da fila..
        /// </summary>
        public static string CallingNextPassword {
            get {
                return ResourceManager.GetString("CallingNextPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senha {0} transferida da fila “{1}” para “{2}”.
        /// </summary>
        public static string HistoryQueueChanged {
            get {
                return ResourceManager.GetString("HistoryQueueChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senha {0} marcada como atendida.
        /// </summary>
        public static string HistoryServed {
            get {
                return ResourceManager.GetString("HistoryServed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senha {0} transferida de “{1}” para “{2}”.
        /// </summary>
        public static string HistoryTransferred {
            get {
                return ResourceManager.GetString("HistoryTransferred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não há senhas na fila. Aguarde..
        /// </summary>
        public static string NoPasswordsInQueue {
            get {
                return ResourceManager.GetString("NoPasswordsInQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possível criar o Local de Atendimento.
        /// </summary>
        public static string UnableCreateServiceLocation {
            get {
                return ResourceManager.GetString("UnableCreateServiceLocation", resourceCulture);
            }
        }
    }
}
