// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Totem.Infra.Data;

#nullable disable

namespace Totem.Infra.Migrations
{
    [DbContext(typeof(TotemDbContext))]
    [Migration("20260203233212_AddServiceTypes")]
    partial class AddServiceTypes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Totem")
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Totem.Domain.Aggregates.PasswordAggregate.Password", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("PasswordId");

                    b.Property<DateTime?>("AssignedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Code")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Preferential")
                        .HasColumnType("bit");

                    b.Property<Guid>("QueueId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Served")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ServiceLocationId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("QueueId");

                    b.HasIndex("ServiceLocationId");

                    b.ToTable("Passwords", "Totem");
                });

            modelBuilder.Entity("Totem.Domain.Aggregates.PasswordAggregate.PasswordHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("PasswordHistoryId");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("NewValue")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("OldValue")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PasswordHistoryEventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("PasswordId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PasswordId");

                    b.ToTable("PasswordHistory", "Totem");
                });

            modelBuilder.Entity("Totem.Domain.Aggregates.QueueAggregate.Queue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("QueueId");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<Guid?>("ServiceLocationId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ServiceLocationId");

                    b.ToTable("Queues", "Totem");
                });

            modelBuilder.Entity("Totem.Domain.Aggregates.ServiceLocationAggregate.ServiceLocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ServiceLocationId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<int?>("Number")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ServiceLocations", "Totem");
                });

            modelBuilder.Entity("Totem.Domain.Aggregates.ServiceTypeAggregate.ServiceType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ServiceTypeId");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Icon")
                        .HasColumnType("varchar(100)");

                    b.Property<Guid>("TargetQueueId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TicketPrefix")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("TicketPrefix")
                        .IsUnique();

                    b.HasIndex("Title", "TargetQueueId")
                        .IsUnique();

                    b.ToTable("ServiceTypes", "Totem");
                });

            modelBuilder.Entity("Totem.Domain.Aggregates.PasswordAggregate.Password", b =>
                {
                    b.HasOne("Totem.Domain.Aggregates.QueueAggregate.Queue", "Queue")
                        .WithMany("Passwords")
                        .HasForeignKey("QueueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Totem.Domain.Aggregates.ServiceLocationAggregate.ServiceLocation", "ServiceLocation")
                        .WithMany()
                        .HasForeignKey("ServiceLocationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Queue");

                    b.Navigation("ServiceLocation");
                });

            modelBuilder.Entity("Totem.Domain.Aggregates.QueueAggregate.Queue", b =>
                {
                    b.HasOne("Totem.Domain.Aggregates.ServiceLocationAggregate.ServiceLocation", null)
                        .WithMany("Queues")
                        .HasForeignKey("ServiceLocationId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Totem.Domain.Aggregates.QueueAggregate.Queue", b =>
                {
                    b.Navigation("Passwords");
                });

            modelBuilder.Entity("Totem.Domain.Aggregates.ServiceLocationAggregate.ServiceLocation", b =>
                {
                    b.Navigation("Queues");
                });
#pragma warning restore 612, 618
        }
    }
}
